spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: embarkx # Changed from markx
    password: password # Changed from markx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8081
